server:
  port: 8080

spring:
  application:
    name: hwsem2MTS
  profiles:
    active: test

logging:
  level:
    org.app.hwsem2mts: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "shutdown"
      base-path: /admin/actuator