spring:
  application:
    name: hwsem2MTS
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://localhost:5432/courses_app
    username: postgres
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.app.hwsem2mts: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "shutdown"
      base-path: /admin/actuator

server:
  port: 8080
  tomcat:
    threads:
      min-spare: 10
      max: 210

resilience4j.ratelimiter:
  instances:
    rateLimiterAPI:
      limitForPeriod: 5
      limitRefreshPeriod: 10s
      timeoutDuration: 0
resilience4j.circuitbreaker:
  instances:
    CircuitBreakerAPI:
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: count_based
      slidingWindowSize: 10
